apiVersion: batch/v1
kind: Job
metadata:
  name: create-secret-if-missing
  namespace: {{ .Values.global.namespace default 'opnform' }}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: check-and-create-secret
        image: bitnami/kubectl:latest
        command:
        - /bin/bash
        - -c
        - |
          if kubectl get secret my-secret -n default; then
            echo "Secret already exists. Exiting.";
            exit 0;
          else
            echo "Secret not found. Creating...";
            kubectl create secret generic my-secret \
              --from-literal=username=admin \
              --from-literal=password=supersecret \
              -n default
          fi
