apiVersion: v1
kind: Secret
metadata:
  name: api-env-general
  namespace: {{ .Values.global.namespace default 'opnform' }}
type: Opaque
data:
  APP_KEY: "base64:"{{ default ((lookup "v1" "Secret" .Release.Namespace "api-env-general").data.APP_KEY | b64dec | default (openssl rand -base64 32)) }}
  FRONT_API_SECRET: {{ default ((lookup "v1" "Secret" .Release.Namespace "api-env-general").data.FRONT_API_SECRET | b64dec | default (openssl rand -base64 32)) }}
  JWT_SECRET: {{ default ((lookup "v1" "Secret" .Release.Namespace "api-env-general").data.JWT_SECRET | b64dec | default (openssl rand -base64 32)) }}
  MIX_PUSHER_APP_CLUSTER: {{ .Values.api.config.mix.pusherAppCluster default mt1 }}
  MIX_PUSHER_APP_KEY: {{ .Values.api.config.mix.pusherAppKey default "" }}
  MUX_API_TOKEN: {{ .Values.api.config.mux.apiToken default "" }}
  MUX_WORKSPACE_ID: {{ .Values.api.config.mux.workspaceId default "" }}
  OPEN_AI_API_KEY: {{ .Values.api.config.openAI.apiKey default "" }}
  PUSHER_APP_CLUSTER: {{ .Values.api.config.pusher.appCluster default "" }}
  PUSHER_APP_ID: {{ .Values.api.config.pusher.appId default "" }}
  PUSHER_APP_KEY: {{ .Values.api.config.pusher.appKey default "" }}
  PUSHER_APP_SECRET: {{ .Values.api.config.pusher.appSecret default "" }}