apiVersion: v1
kind: Secret
metadata:
  name: api-env-aws
  namespace: {{ .Values.global.namespace default 'opnform' }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.api.config.aws.accessKeyId default "" | quote }}
  AWS_BUCKET: {{ .Values.api.config.aws.bucket default "" | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.api.config.aws.secretAccessKey default "" | quote }}
  AWS_DEFAULT_REGION: {{ .Values.api.config.aws.region default 'us-east-1' | quote }}