apiVersion: v1
kind: Secret
metadata:
  name: psql-credentials
  namespace: {{ .Values.global.namespace default 'opnform' }}
type: Opaque
data:
  username: {{ .Values.db.config.username default 'postgres' }}
  database: {{ .Values.db.config.dbname default 'postgres' }}
  connection: {{ .Values.db.config.connection default 'psql' }}
# This should generate the password on first run or set it if provided in the values.yaml
  password: {{ .Values.db.config.password | default ((lookup "v1" "Secret" .Release.Namespace "psql-credentials").data.password | b64dec | default (openssl rand -base64 20)) | quote }}