apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-worker
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
    spec:
      containers:
        - name: opnform-api-worker
          image: jhumanj/opnform-api:latest
          envFrom:
          - configMapRef:
              name: api-env
          env:
          - name: APP_ENV
            value: production
          - name: IS_API_WORKER
            value: "true"
          command: ["php", "artisan", "queue:work"]
      restartPolicy: Always
