apiVersion: apps/v1
kind: Deployment
metadata:
  namepspace: {{ .Values.global.namespace default 'opnform' }}
  name: ingress
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
    spec:
      containers:
        {{- if .Values.global.registry.url }}
        - image: {{ .Values.global.registry.url }}/{{ .Values.api.image default nginx }}:{{ .Values.api.tag default 1 }}
        {{- else }}
        - image: {{ .Values.api.image default nginx }}:{{ .Values.api.tag default 1 }}
        {{- end }}
          name: opnform-ingress
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/templates/default.conf.template
              name: ingress-cm0
              subPath: default.conf.template
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: nginx.conf
                path: default.conf.template
            name: ingress-cm0
          name: ingress-cm0
