apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namepspace: {{ .Values.global.namespace default 'opnform' }}
  name: postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.volume.size default '10G' }}
