apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  template:
    spec:
      containers:
        - image: redis:7
          name: opnform-redis
      restartPolicy: Always
