apiVersion: apps/v1
kind: Deployment
metadata:
  namepspace: {{ .Values.global.namespace default 'opnform' }}
  name: ui
spec:
  replicas: 1
  template:
    metadata:
    spec:
      containers:
        - envFrom:
          - configMapRef:
              name: ui-env
        {{- if .Values.global.registry.url }}
          image: {{ .Values.global.registry.url }}/{{ .Values.api.image default jhumanj/opnform-client }}:{{ .Values.api.tag default latest }}
        {{- else }}
          image: {{ .Values.api.image default jhumanj/opnform-client }}:{{ .Values.api.tag default latest }}
        {{- end }}
          name: opnform-client
      restartPolicy: Always
